"""
Proposal Generator — the creative (untrusted) LLM agent.

Uses an LLM to generate diverse search hypotheses based on the current
best itinerary, config constraints, and exploration history.
All proposals are later validated by the deterministic validator.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .config import AutofareConfig, NEARBY_AIRPORTS, AIRPORT_COUNTRY
from .flight_search import SearchQuery
from .validator import ScoredItinerary

logger = logging.getLogger("autofare.proposer")


# ---------------------------------------------------------------------------
# Proposal data type
# ---------------------------------------------------------------------------

@dataclass
class Proposal:
    """A proposed search variation generated by the LLM or built-in strategies."""
    queries: List[SearchQuery]
    strategy: str  # category label
    reasoning: str  # why this might help
    source: str = "llm"  # "llm" or "builtin"


# ---------------------------------------------------------------------------
# Built-in (deterministic) proposal strategies
# ---------------------------------------------------------------------------

class BuiltinStrategies:
    """
    Generates proposals using deterministic logic — no LLM needed.
    These cover the standard tricks that always make sense to try.
    """

    def __init__(self, config: AutofareConfig):
        self.config = config

    def generate_all(
        self,
        iteration: int,
        explored: set,
    ) -> List[Proposal]:
        """Generate all applicable built-in proposals."""
        proposals = []

        if self.config.strategies.date_shifts:
            proposals.extend(self._date_shift_proposals(explored))

        if self.config.strategies.alternate_airports:
            proposals.extend(self._alternate_airport_proposals(explored))

        if self.config.strategies.hub_routing:
            proposals.extend(self._hub_routing_proposals(explored))

        if self.config.strategies.split_tickets:
            proposals.extend(self._split_ticket_proposals(explored))

        return proposals

    def _date_shift_proposals(self, explored: set) -> List[Proposal]:
        """Shift departure/return dates within the flex window."""
        proposals = []
        route = self.config.route
        cabin = self.config.constraints.cabin

        all_dep_dates = route.departure_date.all_dates()
        target_dep = route.departure_date.target

        for origin in route.origins:
            for dest in route.destinations:
                for dep_date in all_dep_dates:
                    if dep_date == target_dep:
                        continue  # skip target (already in baseline)
                    key = f"date_shift:{origin}:{dest}:{dep_date}"
                    if key in explored:
                        continue
                    explored.add(key)

                    queries = [SearchQuery(
                        origin=origin,
                        destination=dest,
                        date=dep_date,
                        cabin=cabin,
                        trip_type="one-way",
                        max_stops=self.config.constraints.max_stops,
                        label=f"date_shift {dep_date}",
                    )]

                    proposals.append(Proposal(
                        queries=queries,
                        strategy="date_shift",
                        reasoning=f"Try departing on {dep_date} instead of {target_dep}",
                        source="builtin",
                    ))

        return proposals

    def _alternate_airport_proposals(self, explored: set) -> List[Proposal]:
        """Try nearby airports for origin and/or destination."""
        proposals = []
        route = self.config.route
        cabin = self.config.constraints.cabin
        dep_date = route.departure_date.target

        for origin in route.origins:
            nearby_origins = NEARBY_AIRPORTS.get(origin, [])
            for alt_origin in nearby_origins:
                for dest in route.destinations:
                    key = f"alt_origin:{alt_origin}:{dest}:{dep_date}"
                    if key in explored:
                        continue
                    explored.add(key)

                    proposals.append(Proposal(
                        queries=[SearchQuery(
                            origin=alt_origin,
                            destination=dest,
                            date=dep_date,
                            cabin=cabin,
                            trip_type="one-way",
                            max_stops=self.config.constraints.max_stops,
                            label=f"alt_origin {alt_origin}→{dest}",
                        )],
                        strategy="alternate_airport",
                        reasoning=f"Fly from nearby {alt_origin} instead of {origin}",
                        source="builtin",
                    ))

        for dest in route.destinations:
            nearby_dests = NEARBY_AIRPORTS.get(dest, [])
            for alt_dest in nearby_dests:
                for origin in route.origins:
                    key = f"alt_dest:{origin}:{alt_dest}:{dep_date}"
                    if key in explored:
                        continue
                    explored.add(key)

                    proposals.append(Proposal(
                        queries=[SearchQuery(
                            origin=origin,
                            destination=alt_dest,
                            date=dep_date,
                            cabin=cabin,
                            trip_type="one-way",
                            max_stops=self.config.constraints.max_stops,
                            label=f"alt_dest {origin}→{alt_dest}",
                        )],
                        strategy="alternate_airport",
                        reasoning=f"Fly into nearby {alt_dest} instead of {dest}",
                        source="builtin",
                    ))

        return proposals

    def _hub_routing_proposals(self, explored: set) -> List[Proposal]:
        """Try routing through known hub airports (split into two one-ways)."""
        proposals = []
        route = self.config.route
        cabin = self.config.constraints.cabin
        dep_date = route.departure_date.target
        forbidden = set(self.config.constraints.forbidden_transit_countries)

        for origin in route.origins:
            for dest in route.destinations:
                for hub in self.config.strategies.hub_airports:
                    # Skip if hub is origin or destination
                    if hub in (origin, dest):
                        continue
                    # Skip if hub country is forbidden
                    hub_country = AIRPORT_COUNTRY.get(hub, "")
                    if hub_country in forbidden:
                        continue

                    key = f"hub:{origin}:{hub}:{dest}:{dep_date}"
                    if key in explored:
                        continue
                    explored.add(key)

                    proposals.append(Proposal(
                        queries=[
                            SearchQuery(
                                origin=origin,
                                destination=hub,
                                date=dep_date,
                                cabin=cabin,
                                trip_type="one-way",
                                max_stops=self.config.constraints.max_stops,
                                label=f"hub_leg1 {origin}→{hub}",
                            ),
                            SearchQuery(
                                origin=hub,
                                destination=dest,
                                date=dep_date,
                                cabin=cabin,
                                trip_type="one-way",
                                max_stops=self.config.constraints.max_stops,
                                label=f"hub_leg2 {hub}→{dest}",
                            ),
                        ],
                        strategy="hub_routing",
                        reasoning=f"Split ticket via {hub} hub",
                        source="builtin",
                    ))

        return proposals

    def _split_ticket_proposals(self, explored: set) -> List[Proposal]:
        """Try splitting into two separate one-way tickets on the same route."""
        # This is mainly useful for round-trips where one-way pricing
        # might be cheaper than round-trip on different carriers
        proposals = []
        route = self.config.route
        cabin = self.config.constraints.cabin

        if route.trip_type != "round-trip" or route.return_date is None:
            return proposals

        dep_date = route.departure_date.target
        ret_date = route.return_date.target

        for origin in route.origins:
            for dest in route.destinations:
                key = f"split_rt:{origin}:{dest}:{dep_date}:{ret_date}"
                if key in explored:
                    continue
                explored.add(key)

                proposals.append(Proposal(
                    queries=[
                        SearchQuery(
                            origin=origin,
                            destination=dest,
                            date=dep_date,
                            cabin=cabin,
                            trip_type="one-way",
                            max_stops=self.config.constraints.max_stops,
                            label=f"split_outbound {origin}→{dest}",
                        ),
                        SearchQuery(
                            origin=dest,
                            destination=origin,
                            date=ret_date,
                            cabin=cabin,
                            trip_type="one-way",
                            max_stops=self.config.constraints.max_stops,
                            label=f"split_return {dest}→{origin}",
                        ),
                    ],
                    strategy="split_ticket",
                    reasoning="Split round-trip into two one-way tickets",
                    source="builtin",
                ))

        return proposals


# ---------------------------------------------------------------------------
# LLM-based proposal generator
# ---------------------------------------------------------------------------

PROPOSAL_SYSTEM_PROMPT = """\
You are an expert flight search optimizer. Your job is to propose creative \
search variations that might find cheaper business class (or specified cabin) flights.

You will be given:
1. The search configuration (origin, destination, dates, constraints)
2. The current best itinerary found so far
3. A log of strategies already tried

Propose {n_proposals} new search variations. For each, specify:
- strategy: category (date_shift, alternate_airport, hub_routing, split_ticket, \
open_jaw, positioning, creative)
- origin: IATA airport code
- destination: IATA airport code
- date: YYYY-MM-DD
- trip_type: "one-way" or "round-trip"
- return_date: YYYY-MM-DD (only for round-trip)
- reasoning: brief explanation of why this might be cheaper

Think creatively:
- Try positioning via cheaper hubs (BKK, IST, CDG, etc.)
- Consider nearby airports with better pricing
- Mix airlines / alliances for different legs
- Try dates ±1-3 days from target
- Consider open-jaw (fly into one city, out of another)
- Think about which carriers price business class competitively on specific routes

IMPORTANT CONSTRAINTS:
{constraints}

Respond with ONLY a JSON array of proposal objects. No other text."""


def _build_llm_prompt(
    config: AutofareConfig,
    best_so_far: Optional[ScoredItinerary],
    explored_strategies: List[str],
    n_proposals: int,
) -> str:
    """Build the user prompt for the LLM proposal generator."""
    route = config.route
    constraints_text = []
    if config.constraints.forbidden_transit_countries:
        constraints_text.append(
            f"- NO transit through countries: {', '.join(config.constraints.forbidden_transit_countries)}"
        )
    if config.passengers.passport_nationality:
        constraints_text.append(
            f"- Passenger passport: {config.passengers.passport_nationality}"
        )
    if config.constraints.max_stops is not None:
        constraints_text.append(f"- Max stops: {config.constraints.max_stops}")
    if config.constraints.forbidden_airlines:
        constraints_text.append(
            f"- Forbidden airlines: {', '.join(config.constraints.forbidden_airlines)}"
        )

    best_text = "No baseline found yet."
    if best_so_far:
        best_text = (
            f"Current best: {best_so_far.summary()}\n"
            f"  Price: ${best_so_far.price:.0f}, Score: {best_so_far.score:.0f}"
        )

    explored_text = "None yet." if not explored_strategies else "\n".join(
        f"- {s}" for s in explored_strategies[-20:]  # last 20 to keep prompt size down
    )

    return f"""## Search Configuration
- Origins: {', '.join(route.origins)}
- Destinations: {', '.join(route.destinations)}
- Departure: {route.departure_date.target} (±{route.departure_date.flex_days} days)
- Return: {route.return_date.target if route.return_date else 'N/A (one-way)'}
- Cabin: {config.constraints.cabin}
- Trip type: {route.trip_type}

## Current Best
{best_text}

## Strategies Already Tried
{explored_text}

## Available Hub Airports
{', '.join(config.strategies.hub_airports)}

Propose {n_proposals} new, creative search variations that haven't been tried yet."""


class LLMProposer:
    """Uses an LLM to generate creative search proposals."""

    def __init__(self, config: AutofareConfig):
        self.config = config

    def generate(
        self,
        best_so_far: Optional[ScoredItinerary],
        explored_strategies: List[str],
        n_proposals: int = 8,
    ) -> List[Proposal]:
        """Generate proposals using the configured LLM."""
        llm_config = self.config.llm

        constraints_text = ""
        if self.config.constraints.forbidden_transit_countries:
            constraints_text += (
                f"- NO transit through: "
                f"{', '.join(self.config.constraints.forbidden_transit_countries)}\n"
            )
        if self.config.passengers.passport_nationality:
            constraints_text += (
                f"- Passenger passport: {self.config.passengers.passport_nationality}\n"
            )

        system = PROPOSAL_SYSTEM_PROMPT.format(
            n_proposals=n_proposals,
            constraints=constraints_text or "None specified.",
        )
        user_msg = _build_llm_prompt(
            self.config, best_so_far, explored_strategies, n_proposals
        )

        try:
            raw_response = self._call_llm(system, user_msg)
            return self._parse_response(raw_response)
        except Exception as e:
            logger.error(f"LLM proposal generation failed: {e}")
            return []

    def _call_llm(self, system: str, user_msg: str) -> str:
        """Call the LLM API and return raw text response."""
        llm_config = self.config.llm

        if llm_config.provider == "anthropic":
            return self._call_anthropic(system, user_msg)
        elif llm_config.provider == "openai":
            return self._call_openai(system, user_msg)
        else:
            raise ValueError(f"Unknown LLM provider: {llm_config.provider}")

    def _call_anthropic(self, system: str, user_msg: str) -> str:
        """Call Anthropic's Claude API."""
        import anthropic

        client = anthropic.Anthropic(api_key=self.config.llm.api_key)
        message = client.messages.create(
            model=self.config.llm.model,
            max_tokens=self.config.llm.max_tokens,
            temperature=self.config.llm.temperature,
            system=system,
            messages=[{"role": "user", "content": user_msg}],
        )
        return message.content[0].text

    def _call_openai(self, system: str, user_msg: str) -> str:
        """Call OpenAI's API."""
        import openai

        client = openai.OpenAI(api_key=self.config.llm.api_key)
        response = client.chat.completions.create(
            model=self.config.llm.model,
            temperature=self.config.llm.temperature,
            max_tokens=self.config.llm.max_tokens,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_msg},
            ],
        )
        return response.choices[0].message.content or ""

    def _parse_response(self, raw: str) -> List[Proposal]:
        """Parse LLM JSON response into Proposal objects."""
        # Extract JSON array from response (might have markdown fences)
        json_match = re.search(r'\[.*\]', raw, re.DOTALL)
        if not json_match:
            logger.warning("No JSON array found in LLM response")
            return []

        try:
            items = json.loads(json_match.group(0))
        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse LLM JSON: {e}")
            return []

        proposals = []
        cabin = self.config.constraints.cabin

        for item in items:
            if not isinstance(item, dict):
                continue

            origin = item.get("origin", "").strip().upper()
            destination = item.get("destination", "").strip().upper()
            date_str = item.get("date", "").strip()
            strategy = item.get("strategy", "creative")
            reasoning = item.get("reasoning", "")
            trip_type = item.get("trip_type", "one-way")
            return_date = item.get("return_date")

            if not origin or not destination or not date_str:
                continue
            if len(origin) != 3 or len(destination) != 3:
                continue

            queries = [SearchQuery(
                origin=origin,
                destination=destination,
                date=date_str,
                cabin=cabin,
                trip_type=trip_type,
                return_date=return_date,
                max_stops=self.config.constraints.max_stops,
                label=f"llm_{strategy} {origin}→{destination}",
            )]

            proposals.append(Proposal(
                queries=queries,
                strategy=strategy,
                reasoning=reasoning,
                source="llm",
            ))

        logger.info(f"LLM proposed {len(proposals)} valid search variations")
        return proposals


# ---------------------------------------------------------------------------
# Unified proposer that combines built-in and LLM strategies
# ---------------------------------------------------------------------------

class ProposalGenerator:
    """Combines built-in and LLM-based proposal generation."""

    def __init__(self, config: AutofareConfig):
        self.config = config
        self.builtin = BuiltinStrategies(config)
        self.llm_proposer = LLMProposer(config)
        self.explored: set = set()
        self.explored_labels: List[str] = []
        self._builtin_generated = False

    def generate(
        self,
        iteration: int,
        best_so_far: Optional[ScoredItinerary],
        budget_remaining: int,
    ) -> List[Proposal]:
        """
        Generate proposals for the current iteration.

        First iteration: mostly built-in strategies.
        Later iterations: lean more on LLM creativity.
        """
        proposals = []
        n_target = self.config.loop.proposals_per_iteration

        # First pass: built-in strategies (only generate once)
        if not self._builtin_generated:
            builtin = self.builtin.generate_all(iteration, self.explored)
            proposals.extend(builtin)
            self._builtin_generated = True
            logger.info(f"Built-in strategies generated {len(builtin)} proposals")

        # If we still have budget and it's not the first iteration, use LLM
        if iteration > 0 and len(proposals) < n_target:
            n_llm = min(n_target - len(proposals), budget_remaining)
            if n_llm > 0:
                try:
                    llm_proposals = self.llm_proposer.generate(
                        best_so_far=best_so_far,
                        explored_strategies=self.explored_labels,
                        n_proposals=n_llm,
                    )
                    proposals.extend(llm_proposals)
                except Exception as e:
                    logger.warning(f"LLM generation failed, using built-in only: {e}")

        # Trim to budget
        if len(proposals) > budget_remaining:
            proposals = proposals[:budget_remaining]

        # Track what we've explored
        for p in proposals:
            label = f"{p.strategy}: {p.reasoning[:80]}"
            self.explored_labels.append(label)

        return proposals
